global:
  scrape_interval: 1s

scrape_configs:
  - job_name: "node_exporter"
    static_configs:
      - targets: ["node_exporter:9100"]

  - job_name: "loopback4"
    static_configs:
      - targets: ["192.168.15.37:9464"]
